### ISSUE TITLE
XGD Directories

### ISSUE THREAD

**Issue by vincentqb** [bashdot/bashdot#5]
Neovim uses dotfiles within subfolders, see [here](https://neovim.io/doc/user/starting.html#standard-path). With bashdot, I move the whole `.local` and `.config` folder within my dotfiles repository, but only version the files that are needed (e.g. Neovim's). Is there a different way of doing this with bashdot that would avoid moving the whole directory?

**Comment by weavenet** [comment]
Right now, I don't know of a better way.  Bashdot only works on there root level, linking files or directories.  I've typically added directories, then gitignored stuff I don't want versioned.  This is not ideal as it's easy to forgot or not keep up.

One option could be to allow for adding a .bashdotdescend file (or something like that) which tell bash dot to descend this directory and link within it vs linking the entire directory, however I'm not sure if that would result in a better result.  Thoughts?

**Comment by vincentqb** [comment]
Without a configuration file, I don't find a natural way of doing cherry-picking configuration files in subfolders :) Something similar was done [here](https://pypi.org/project/dotfiles/) with "packages".
